<?php

// Ensure that autoload.php is generated by Composer
require 'libs/TCPDF/vendor/autoload.php';

use TCPDF\TCPDF; // Adjust the namespace as needed

class SKGuruPDF extends TCPDF
{
    private $namaGuru;
    private $nip;
    private $tanggalSurat;

    // Constructor to initialize teacher data
    public function __construct($namaGuru, $nip, $tanggalSurat)
    {
        parent::__construct();

        $this->namaGuru = $namaGuru;
        $this->nip = $nip;
        $this->tanggalSurat = $tanggalSurat;
    }

    // Method to create the content of the decision letter
    private function createContent()
    {
        $content = "Surat Keputusan\n";
        $content .= "Nomor: ________/SK/Guru/" . date('Y') . "\n\n";
        $content .= "Diberikan kepada:\n";
        $content .= "Nama\t\t: " . $this->namaGuru . "\n";
        $content .= "NIP\t\t: " . $this->nip . "\n\n";
        $content .= "Tanggal Surat\t: " . $this->tanggalSurat . "\n\n";
        $content .= "Dengan ini, kami menyatakan bahwa " . $this->namaGuru . " diterima sebagai guru di sekolah ini.\n";
        $content .= "Demikian surat keputusan ini kami buat untuk dapat dipergunakan sebagaimana mestinya.\n\n";
        $content .= "Dikeluarkan di\t: [Lokasi]\n";
        $content .= "Pada tanggal\t: " . date('d F Y') . "\n\n";
        $content .= "Kepala Sekolah,\n\n\n";
        $content .= "[Nama Kepala Sekolah]\n";

        return $content;
    }

    // Method to add content to the PDF page
    public function createSKGuruPDF()
    {
        $this->AddPage();
        $content = $this->createContent();
        $this->writeHTML($content, true, false, true, false, '');

        // Adjust the filename as needed
        $filename = 'SK_Guru_' . str_replace(' ', '_', $this->namaGuru) . '.pdf';
        $this->Output($filename, 'D');
    }
}

// Example usage
$namaGuru = "John Doe";
$nip = "123456789";
$tanggalSurat = "01 Januari 2023";

// Create SKGuruPDF object
$pdf = new SKGuruPDF($namaGuru, $nip, $tanggalSurat);

// Create and save the decision letter as a PDF file
$pdf->createSKGuruPDF();
